/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRegistrarSyncJobsRouteImport } from './routes/api/registrar-sync-jobs'
import { Route as ApiRegistrarDomainsRouteImport } from './routes/api/registrar-domains'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRecordsRouteImport } from './routes/_app.records'
import { Route as AppDomainsRouteImport } from './routes/_app.domains'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBindRouteImport } from './routes/_app.bind'
import { Route as AppBackupRouteImport } from './routes/_app.backup'
import { Route as ApiRegistrarDomainsIdRouteImport } from './routes/api/registrar-domains/$id'
import { Route as ApiRegistrarsIdSyncDomainsRouteImport } from './routes/api/registrars/$id/sync-domains'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistrarSyncJobsRoute = ApiRegistrarSyncJobsRouteImport.update({
  id: '/api/registrar-sync-jobs',
  path: '/api/registrar-sync-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistrarDomainsRoute = ApiRegistrarDomainsRouteImport.update({
  id: '/api/registrar-domains',
  path: '/api/registrar-domains',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordsRoute = AppRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainsRoute = AppDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBindRoute = AppBindRouteImport.update({
  id: '/bind',
  path: '/bind',
  getParentRoute: () => AppRoute,
} as any)
const AppBackupRoute = AppBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AppRoute,
} as any)
const ApiRegistrarDomainsIdRoute = ApiRegistrarDomainsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiRegistrarDomainsRoute,
} as any)
const ApiRegistrarsIdSyncDomainsRoute =
  ApiRegistrarsIdSyncDomainsRouteImport.update({
    id: '/api/registrars/$id/sync-domains',
    path: '/api/registrars/$id/sync-domains',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/unlock': typeof UnlockRoute
  '/backup': typeof AppBackupRoute
  '/bind': typeof AppBindRoute
  '/dashboard': typeof AppDashboardRoute
  '/domains': typeof AppDomainsRoute
  '/records': typeof AppRecordsRoute
  '/settings': typeof AppSettingsRoute
  '/api/registrar-domains': typeof ApiRegistrarDomainsRouteWithChildren
  '/api/registrar-sync-jobs': typeof ApiRegistrarSyncJobsRoute
  '/api/registrar-domains/$id': typeof ApiRegistrarDomainsIdRoute
  '/api/registrars/$id/sync-domains': typeof ApiRegistrarsIdSyncDomainsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unlock': typeof UnlockRoute
  '/backup': typeof AppBackupRoute
  '/bind': typeof AppBindRoute
  '/dashboard': typeof AppDashboardRoute
  '/domains': typeof AppDomainsRoute
  '/records': typeof AppRecordsRoute
  '/settings': typeof AppSettingsRoute
  '/api/registrar-domains': typeof ApiRegistrarDomainsRouteWithChildren
  '/api/registrar-sync-jobs': typeof ApiRegistrarSyncJobsRoute
  '/api/registrar-domains/$id': typeof ApiRegistrarDomainsIdRoute
  '/api/registrars/$id/sync-domains': typeof ApiRegistrarsIdSyncDomainsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/_app/backup': typeof AppBackupRoute
  '/_app/bind': typeof AppBindRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/domains': typeof AppDomainsRoute
  '/_app/records': typeof AppRecordsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/registrar-domains': typeof ApiRegistrarDomainsRouteWithChildren
  '/api/registrar-sync-jobs': typeof ApiRegistrarSyncJobsRoute
  '/api/registrar-domains/$id': typeof ApiRegistrarDomainsIdRoute
  '/api/registrars/$id/sync-domains': typeof ApiRegistrarsIdSyncDomainsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unlock'
    | '/backup'
    | '/bind'
    | '/dashboard'
    | '/domains'
    | '/records'
    | '/settings'
    | '/api/registrar-domains'
    | '/api/registrar-sync-jobs'
    | '/api/registrar-domains/$id'
    | '/api/registrars/$id/sync-domains'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unlock'
    | '/backup'
    | '/bind'
    | '/dashboard'
    | '/domains'
    | '/records'
    | '/settings'
    | '/api/registrar-domains'
    | '/api/registrar-sync-jobs'
    | '/api/registrar-domains/$id'
    | '/api/registrars/$id/sync-domains'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/unlock'
    | '/_app/backup'
    | '/_app/bind'
    | '/_app/dashboard'
    | '/_app/domains'
    | '/_app/records'
    | '/_app/settings'
    | '/api/registrar-domains'
    | '/api/registrar-sync-jobs'
    | '/api/registrar-domains/$id'
    | '/api/registrars/$id/sync-domains'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  UnlockRoute: typeof UnlockRoute
  ApiRegistrarDomainsRoute: typeof ApiRegistrarDomainsRouteWithChildren
  ApiRegistrarSyncJobsRoute: typeof ApiRegistrarSyncJobsRoute
  ApiRegistrarsIdSyncDomainsRoute: typeof ApiRegistrarsIdSyncDomainsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/registrar-sync-jobs': {
      id: '/api/registrar-sync-jobs'
      path: '/api/registrar-sync-jobs'
      fullPath: '/api/registrar-sync-jobs'
      preLoaderRoute: typeof ApiRegistrarSyncJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/registrar-domains': {
      id: '/api/registrar-domains'
      path: '/api/registrar-domains'
      fullPath: '/api/registrar-domains'
      preLoaderRoute: typeof ApiRegistrarDomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/records': {
      id: '/_app/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AppRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/domains': {
      id: '/_app/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AppDomainsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bind': {
      id: '/_app/bind'
      path: '/bind'
      fullPath: '/bind'
      preLoaderRoute: typeof AppBindRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backup': {
      id: '/_app/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AppBackupRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/registrar-domains/$id': {
      id: '/api/registrar-domains/$id'
      path: '/$id'
      fullPath: '/api/registrar-domains/$id'
      preLoaderRoute: typeof ApiRegistrarDomainsIdRouteImport
      parentRoute: typeof ApiRegistrarDomainsRoute
    }
    '/api/registrars/$id/sync-domains': {
      id: '/api/registrars/$id/sync-domains'
      path: '/api/registrars/$id/sync-domains'
      fullPath: '/api/registrars/$id/sync-domains'
      preLoaderRoute: typeof ApiRegistrarsIdSyncDomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBackupRoute: typeof AppBackupRoute
  AppBindRoute: typeof AppBindRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDomainsRoute: typeof AppDomainsRoute
  AppRecordsRoute: typeof AppRecordsRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBackupRoute: AppBackupRoute,
  AppBindRoute: AppBindRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDomainsRoute: AppDomainsRoute,
  AppRecordsRoute: AppRecordsRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiRegistrarDomainsRouteChildren {
  ApiRegistrarDomainsIdRoute: typeof ApiRegistrarDomainsIdRoute
}

const ApiRegistrarDomainsRouteChildren: ApiRegistrarDomainsRouteChildren = {
  ApiRegistrarDomainsIdRoute: ApiRegistrarDomainsIdRoute,
}

const ApiRegistrarDomainsRouteWithChildren =
  ApiRegistrarDomainsRoute._addFileChildren(ApiRegistrarDomainsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  UnlockRoute: UnlockRoute,
  ApiRegistrarDomainsRoute: ApiRegistrarDomainsRouteWithChildren,
  ApiRegistrarSyncJobsRoute: ApiRegistrarSyncJobsRoute,
  ApiRegistrarsIdSyncDomainsRoute: ApiRegistrarsIdSyncDomainsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
